-- Insert company data
INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('TechCorp Inc.', '/logos/techcorp.png', 'Technology', 'Large', 4.5, 'San Francisco,New York,Austin', 2010, 'TechCorp Inc. is a leading technology company founded in 2010. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 15000, 'https://www.techcorpinc.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Google', '/logos/google.png', 'Technology', 'Large', 4.4, 'Mountain View,New York,Seattle', 1998, 'Google is a leading technology company founded in 1998. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 156000, 'https://www.google.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Microsoft', '/logos/microsoft.png', 'Technology', 'Large', 4.4, 'Redmond,San Francisco,Austin', 1975, 'Microsoft is a leading technology company founded in 1975. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 221000, 'https://www.microsoft.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Apple', '/logos/apple.png', 'Technology', 'Large', 4.6, 'Cupertino,Austin,Boston', 1976, 'Apple is a leading technology company founded in 1976. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 164000, 'https://www.apple.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Amazon', '/logos/amazon.png', 'E-commerce', 'Large', 4.2, 'Seattle,New York,Austin', 1994, 'Amazon is a leading e-commerce company founded in 1994. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 1540000, 'https://www.amazon.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Tesla', '/logos/tesla.png', 'Automotive', 'Large', 4.3, 'Palo Alto,Austin,Berlin', 2003, 'Tesla is a leading automotive company founded in 2003. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 127855, 'https://www.tesla.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Netflix', '/logos/netflix.png', 'Entertainment', 'Large', 4.7, 'Los Gatos,Los Angeles,New York', 1997, 'Netflix is a leading entertainment company founded in 1997. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 12800, 'https://www.netflix.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Meta', '/logos/meta.png', 'Technology', 'Large', 4.1, 'Menlo Park,Austin,London', 2004, 'Meta is a leading technology company founded in 2004. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 86482, 'https://www.meta.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Spotify', '/logos/spotify.png', 'Music', 'Medium', 4.5, 'Stockholm,New York,Los Angeles', 2006, 'Spotify is a leading music company founded in 2006. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 9800, 'https://www.spotify.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Airbnb', '/logos/airbnb.png', 'Travel', 'Medium', 4.4, 'San Francisco,Portland,Dublin', 2008, 'Airbnb is a leading travel company founded in 2008. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 6800, 'https://www.airbnb.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Uber', '/logos/uber.png', 'Transportation', 'Large', 4.0, 'San Francisco,New York,Amsterdam', 2009, 'Uber is a leading transportation company founded in 2009. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 32800, 'https://www.uber.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Slack', '/logos/slack.png', 'Technology', 'Medium', 4.6, 'San Francisco,New York,Toronto', 2009, 'Slack is a leading technology company founded in 2009. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 2500, 'https://www.slack.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Zoom', '/logos/zoom.svg', 'Technology', 'Medium', 4.5, 'San Jose,Austin,Singapore', 2011, 'Zoom is a leading technology company founded in 2011. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 7400, 'https://www.zoom.us', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Shopify', '/logos/shopify.png', 'E-commerce', 'Medium', 4.3, 'Ottawa,Toronto,San Francisco', 2006, 'Shopify is a leading e-commerce company founded in 2006. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 10000, 'https://www.shopify.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Square', '/logos/square.png', 'Fintech', 'Medium', 4.2, 'San Francisco,Atlanta,New York', 2009, 'Square is a leading fintech company founded in 2009. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 8000, 'https://www.squareup.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Stripe', '/logos/stripe.png', 'Fintech', 'Medium', 4.7, 'San Francisco,New York,London', 2010, 'Stripe is a leading fintech company founded in 2010. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 8000, 'https://www.stripe.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Coinbase', '/logos/coinbase.png', 'Cryptocurrency', 'Medium', 4.1, 'San Francisco,New York,London', 2012, 'Coinbase is a leading cryptocurrency company founded in 2012. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 4700, 'https://www.coinbase.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Twilio', '/logos/twilio.png', 'Technology', 'Medium', 4.3, 'San Francisco,Denver,London', 2008, 'Twilio is a leading technology company founded in 2008. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 9100, 'https://www.twilio.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('GitHub', '/logos/github.png', 'Technology', 'Medium', 4.5, 'San Francisco,Boston,Tokyo', 2008, 'GitHub is a leading technology company founded in 2008. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 3000, 'https://www.github.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Adobe', '/logos/adobe.svg', 'Technology', 'Large', 4.4, 'San Jose,Seattle,New York', 1982, 'Adobe is a leading technology company founded in 1982. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 29239, 'https://www.adobe.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Salesforce', '/logos/salesforce.png', 'Technology', 'Large', 4.3, 'San Francisco,Indianapolis,London', 1999, 'Salesforce is a leading technology company founded in 1999. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 79390, 'https://www.salesforce.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Oracle', '/logos/oracle.png', 'Technology', 'Large', 4.0, 'Austin,Redwood City,Bangalore', 1977, 'Oracle is a leading technology company founded in 1977. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 164000, 'https://www.oracle.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('IBM', '/logos/ibm.svg', 'Technology', 'Large', 4.1, 'Armonk,Austin,Bangalore', 1911, 'IBM is a leading technology company founded in 1911. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 282100, 'https://www.ibm.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Intel', '/logos/intel.png', 'Technology', 'Large', 4.2, 'Santa Clara,Portland,Bangalore', 1968, 'Intel is a leading technology company founded in 1968. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 131900, 'https://www.intel.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('NVIDIA', '/logos/nvidia.png', 'Technology', 'Large', 4.6, 'Santa Clara,Austin,Tel Aviv', 1993, 'NVIDIA is a leading technology company founded in 1993. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 29600, 'https://www.nvidia.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Palantir', '/logos/palantir.png', 'Technology', 'Medium', 4.2, 'Palo Alto,Denver,London', 2003, 'Palantir is a leading technology company founded in 2003. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 3838, 'https://www.palantir.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Snowflake', '/logos/snowflake.png', 'Technology', 'Medium', 4.4, 'Bozeman,San Mateo,Bellevue', 2012, 'Snowflake is a leading technology company founded in 2012. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 6800, 'https://www.snowflake.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Databricks', '/logos/databricks.png', 'Technology', 'Medium', 4.5, 'San Francisco,Amsterdam,Singapore', 2013, 'Databricks is a leading technology company founded in 2013. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 5000, 'https://www.databricks.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Canva', '/logos/canva.png', 'Technology', 'Medium', 4.6, 'Sydney,San Francisco,London', 2012, 'Canva is a leading technology company founded in 2012. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 4000, 'https://www.canva.com', 'SYSTEM');

INSERT INTO companies (name, logo, industry, size, rating, locations, founded, description, employees, website, created_by) VALUES ('Figma', '/logos/figma.png', 'Technology', 'Medium', 4.7, 'San Francisco,New York,London', 2012, 'Figma is a leading technology company founded in 2012. We''re committed to innovation and creating exceptional experiences for our customers and employees.', 1000, 'https://www.figma.com', 'SYSTEM');