CREATE TABLE IF NOT EXISTS `CONTACT_MSG` (
  `CONTACT_ID` int AUTO_INCREMENT  PRIMARY KEY,
  `NAME` varchar(100) NOT NULL,
  `MOBILE_NUM` varchar(10) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SUBJECT` varchar(100) NOT NULL,
  `MESSAGE` varchar(500) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` varchar(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` varchar(50) DEFAULT NULL
);